services:
  sport_site:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $APP_PORT:$APP_PORT
    networks:
      - sport_site_network
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql
    restart: always
    container_name: sport-site-mysql
    env_file:
      - .env
    networks:
      - sport_site_network
    ports:
      - $DB_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: sport-site-rabbitmq
    env_file:
      - .env
    networks:
      - sport_site_network
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  sport_site_network:

volumes:
  rabbitmq_data:
  mysql_data: