services:
  sport_site:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $APP_PORT:$APP_PORT
    networks:
      - sport_site_network
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - sport_site_network
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    env_file:
      - .env
    networks:
      - sport_site_network
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  sport_site_network:

volumes:
  rabbitmq_data:
  postgres_data: